[package]
name = "mdns_webhook_provider"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "webhook_provider"
path = "src/main.rs"

[[bin]]
name = "mdns_server"
path = "src/mdns_server.rs"


[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
clap = { version = "4.6.7", features = ["derive", "env"] }
tokio = { version = "1.53.1", features = ["full" ] }
tokio-util = "0.7.19"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
futures = "0.3.34"
chrono = "0.4.45"
kube = { version = "4.2.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.28.0", features = ["v1_35"] }
axum = { version="0.8.9", features = ["macros"] }
simple-dns = "0.12.0"
socket2 = "0.6.5"
notify = "8.2.0"

[profile.release]
opt-level = "z"     # optimise pour la taille (utile pour scratch/distroless)
lto = true          # link-time optimization, réduit la taille et améliore les perfs
codegen-units = 1   # meilleure optimisation, compilation plus lente
panic = "abort"     # évite d'embarquer le code de unwinding, réduit la taille
strip = true        # supprime les symboles de debug automatiquement (Rust 1.59+)

[target.'cfg(target_env = "musl")']
rustflags = ["-C", "target-feature=+crt-static"]
